version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: readlater_db
      MYSQL_USER: readlater_app
      MYSQL_PASSWORD: secure_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/migrations:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    environment:
      PORT: 8080
      ENV: development
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: readlater_db
      DB_USER: readlater_app
      DB_PASSWORD: secure_password
      JWT_ACCESS_SECRET: your-jwt-secret-key-change-in-production
      JWT_REFRESH_SECRET: your-jwt-refresh-secret-key-change-in-production
      GROQ_API_KEY: ${GROQ_API_KEY:-your-groq-api-key}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY:-your-anthropic-api-key}
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - stockle-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8080/api/v1
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_SECRET: your-nextauth-secret-change-in-production
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID:-your-google-client-id}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET:-your-google-client-secret}
      # サーバーサイド（NextAuth.js）用の内部API URL
      INTERNAL_API_URL: http://backend:8080/api/v1
    depends_on:
      - backend
    networks:
      - stockle-network

volumes:
  mysql_data:
  redis_data:

networks:
  stockle-network:
    driver: bridge